### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 30.0  # Frequency to process sensor data
        sensor_timeout: 0.2
        two_d_mode: true  # Assume your robot operates in a plane
        publish_tf: true  # Whether you want `robot_localization` to publish TFs
        print_diagnostics: false

        map_frame: map                   # Defaults to "map" if unspecified
        odom_frame: odom                 # Defaults to "odom" if unspecified
        base_link_frame: base_footprint  # Defaults to "base_link" if unspecified
        world_frame: odom                # Defaults to the value of odom_frame if unspecified

        odom0: /odom
        odom0_config: [true, true, false, # x, y, z
                       false, false, true, # roll, pitch, yaw
                       true, false, false, # vx, vy, vz
                       false, false, true, # vroll, vpitch, vyaw
                       false, false, false] # ax, ay, az

        imu0: /imu
        imu0_config: [false, false, false, # x, y, z
                      true, true, true, # roll, pitch, yaw
                      false, false, false, # vx, vy, vz
                      true, true, true, # vroll, vpitch, vyaw
                      false, false, false] # ax, ay, az

        imu0_remove_gravitational_acceleration: true