uwaba_controller_server_node:
  ros__parameters:
    wheels_separation: 0.13607
    wheel_radius: 0.0161000025
    base_length: 0.2480000407
    base_width: 0.1058000177
    base_height: 0.0387500003
    main_rate: 100.0
    cmd_vel_back: 30.0
    odom_rate: 30.0
    joint_state_rate: 30.0
    lidar_frame: "laser_frame"
    imu_frame: "imu_frame"
    temperature_frame: "temp_frame"
    battery_frame: "bat_frame"
    uros_encoder_topic: "micro_encoders"
    uros_imu_topic: "micro_imu"
    uros_temperature_topic: "micro_temperature"
    uros_lidar_topic: "micro_laserscan"
    uros_battery_topic: "micro_batterypack"
    odom_topic: "odom"
    joint_states_topic: "new_joint_states"
    cmd_vel_topic: "cmd_vel"
    imu_topic: "imu"
    scan_topic: "scan"
    temperature_topic: "temp"
    battery_pack_topic: "bat"

uwaba_controller_manager_node:
  ros__parameters:
    managed_node_name: "uwaba_controller_server_node"
    micro_ros_node_name: "uWABA"
    agent_checker_rate: 0.1
